# Generated by Django 4.2.5 on 2023-09-04 13:17

from django.db import migrations
from django.contrib.auth.models import User
from AulaWeb.models import Usuario

def criar_root(apps, schemas):
    u = User.objects.create_user(username='Bernardo', email='root@localhost', password='123')
    usr = Usuario()
    usr.user = u
    usr.save()
    


class Migration(migrations.Migration):

    dependencies = [
        ('AulaWeb', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(criar_root)
    ]

